[package]
name = "wrd-tui"
version.workspace = true
edition.workspace = true

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = { version = "0.30.0-alpha.5", features = [
    "all-widgets",
    "unstable-widget-ref",
] }
tui-input = "0.12.1"
wrd-lib = { path = "../wrd-lib" }
